export const SAVE_EMAIL_REQUEST = "SAVE_EMAIL_REQUEST";
export const SAVE_EMAIL_SUCCESS = "SAVE_EMAIL_SUCCESS";
export const SAVE_EMAIL_FAILURE = "SAVE_EMAIL_FAILURE";

export const FETCH_USER_SAVE_RANDOM_EMAIL_REQUEST = "FETCH_USER_SAVE_RANDOM_EMAIL_REQUEST";
export const FETCH_USER_SAVE_RANDOM_EMAIL_SUCCESS = "FETCH_USER_SAVE_RANDOM_EMAIL_SUCCESS";
export const FETCH_USER_SAVE_RANDOM_EMAIL_FAILURE = "FETCH_USER_SAVE_RANDOM_EMAIL_FAILURE";

export const GENERATE_RANDOM_FILTERED_EMAIL_REQUEST = "GENERATE_RANDOM_FILTERED_EMAIL_REQUEST";
export const GENERATE_RANDOM_FILTERED_EMAIL_SUCCESS = "GENERATE_RANDOM_FILTERED_EMAIL_SUCCESS";
export const GENERATE_RANDOM_FILTERED_EMAIL_FAILURE = "GENERATE_RANDOM_FILTERED_EMAIL_FAILURE";


