export const GET_RANDOM_EMAIL_BY_CATEGORY_REQUEST =
  "GET_RANDOM_EMAIL_BY_CATEGORY_REQUEST";
export const GET_RANDOM_EMAIL_BY_CATEGORY_SUCCESS =
  "GET_RANDOM_EMAIL_BY_CATEGORY_SUCCESS";
export const GET_RANDOM_EMAIL_BY_CATEGORY_FAILURE =
  "GET_RANDOM_EMAIL_BY_CATEGORY_FAILURE";
